Sync with Veins master

diff --git a/{{cookiecutter.project_name_as_file_name}}/{{cookiecutter.project_name_as_file_name}}/setenv b/{{cookiecutter.project_name_as_file_name}}/{{cookiecutter.project_name_as_file_name}}/setenv
--- a/{{cookiecutter.project_name_as_file_name}}/{{cookiecutter.project_name_as_file_name}}/setenv
+++ b/{{cookiecutter.project_name_as_file_name}}/{{cookiecutter.project_name_as_file_name}}/setenv
@@ -1,6 +1,7 @@
+#!/bin/echo Error. Aborting. Instead of running this script, please use: source
 
 #
-# Copyright (C) 2017 Rudolf Hornig <rudi@omnetpp.org>
+# Copyright (C) 2020 Christoph Sommer <sommer@ccs-labs.org>
 #
 # Documentation for these modules is at http://veins.car2x.org/
 #
@@ -21,18 +22,14 @@
 # Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 #
 
-#
-# on windows we have to link with the ws2_32 (winsock2) library as it is no longer added to the omnetpp system libraries by default (as of OMNeT++ 5.1)
-# copied from INET Framework (inet-3.6.0) makefrag
-#
-ifeq ($(PLATFORM),win32.x86_64)
-  LIBS += -lws2_32
-  DEFINES += -D{{ cookiecutter.project_name_as_macro_name }}_EXPORT
-  ENABLE_AUTO_IMPORT=-Wl,--enable-auto-import
-  LDFLAGS := $(filter-out $(ENABLE_AUTO_IMPORT), $(LDFLAGS))
-endif
+# Check if called from {{ cookiecutter.project_name }} directory
+test -f print-{{ cookiecutter.project_name_as_file_name }}-version >/dev/null 2>&1
+if [ "$?" -ne 0 ]; then
+	echo 'Error: current working directory does not look like a {{ cookiecutter.project_name }} root directory. Aborting.' >&2
+	return 1
+fi
 
-{{ cookiecutter.project_name_as_macro_name }}_NEED_MSG4 := $(shell echo ${OMNETPP_VERSION} | grep "^5" >/dev/null 2>&1; echo $$?)
-ifneq ($({{ cookiecutter.project_name_as_macro_name }}_NEED_MSG4),0)
-  MSGCOPTS += --msg4
-endif
+# Add Veins directory to PATH
+{{ cookiecutter.project_name_as_macro_name }}_DIR="$(pwd)"
+export PATH="$PATH":"${{ cookiecutter.project_name_as_macro_name }}_DIR/bin"
+
